# Generated by Django 2.2.6 on 2019-10-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.ItemType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Player.Player'),
        ),
    ]
