# Generated by Django 2.2.6 on 2019-10-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(blank=True, max_length=1000, verbose_name='Message Text')),
                ('playerFrom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='playerFrom', to='Player.Player', verbose_name='From')),
                ('playerTo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='playerTo', to='Player.Player', verbose_name='To')),
            ],
        ),
    ]
